### ISSUE TITLE
Move to Appearance?

### ISSUE THREAD

**Issue by Zodiac1978** [Zodiac1978/tl-template-checker#18]

**Comment by glueckpress** [comment]
:+1:

**Comment by staude** [comment]
:+1:

**Comment by Zodiac1978** [comment]
After discussion on WordCamp Cologne Contributor Day we want to add a Child Theme Check button on every Child Theme under Appearance - Themes.
Additionally the menu entry stays under Tools (or Appearance).
(the crowd has decided for Tools instead of Appearance, but I showed them Tools in my demo, so maybe they just to be polite ...)
I thin there was a third option to add a link to the Child Theme Check, but I do not remember. Anyone?

**Comment by Zodiac1978** [comment]
Now I remember: We wanted to add the link to the plugin box itself. (After Activate/Deactive and so on).

**Comment by glueckpress** [comment]
+1 for Tools then. I like the idea of having an action link directly at any child theme on Appearance → Themes. The value of an additional link via `{$prefix}plugin_action_links_{$plugin_file}` I don’t see.

**Comment by Zodiac1978** [comment]
@glueckpress Well it is just another link to the main location of the functionality. So why not?

I will split this up and open a new issue for checking inactive child themes.

Todo for this issue:
* add link on plugin page

Child Theme Check remains in Tools until we get more feedback.
