### ISSUE TITLE
Show Child Theme Check even if there is no active Child Theme

### ISSUE THREAD

**Issue by Zodiac1978** [Zodiac1978/tl-template-checker#26]
At the moment we just show the Child Theme Check if the active theme is a child theme.

We should not confuse the people with not showing the link after activation. We should display a message explaining the problem.

**Comment by staude** [comment]
Only on plugin activation page or with each call of appearance?

**Comment by Zodiac1978** [comment]
Can't follow you.

At the moment we just add the menu entry if there is an active child theme.

The link on the plugin page links to http://localhost:8888/wp-dev/wp-admin/tools.php?page=tplc-status and if there is no active child theme we get a permission error.

You can try that: Activate a parent theme and then follow the link on the plugin page.

I want to avoid the WP error. Instead of that, we can just display a message like " You have to activate a child theme, otherwise this plugin has nothing to do ... ;)"
