### ISSUE TITLE
Tidy up on deletion

### ISSUE THREAD

**Issue by Zodiac1978** [Zodiac1978/tl-template-checker#27]
We store an option in the DB, so I think we should tidy up after deletion of the plugin.

Maybe @hinnerk-a can help with that?

See: https://codex.wordpress.org/Function_Reference/register_uninstall_hook#uninstall.php

Looks like we just have to add a uninstall.php with:
```php
//if uninstall not called from WordPress exit
if ( !defined( 'WP_UNINSTALL_PLUGIN' ) ) 
    exit();

$option_name = 'tplc_admin_notices';
delete_option( $option_name );
```
Further reading:
https://github.com/woothemes/woocommerce/blob/5ef335b169ff4e19a4c5b393963a369446922b0c/uninstall.php

Feedback is appreciated. :)

**Comment by hinnerk-a** [comment]
@Zodiac1978 This is absolutely correct.

This - imho - looks prettier:
    delete_option( 'tplc_admin_notices' );

The following line removes my recently added theme mod, but unfortunately removes only the one of the currently active theme while uninstalling the plugin:
    remove_theme_mod( 'tl_latest_core_version' );

But as both options do not contain sensitive data like API keys, passwords etc, it's just a few bytes left in the DB.
