### ISSUE TITLE
add GitHub Updater support

### ISSUE THREAD

**Issue by staude** [Zodiac1978/tl-template-checker#46]
add GitHub Updater support

**Comment by Zodiac1978** [comment]
Is this allowed in the wp.org directory?

**Comment by staude** [comment]
i have the metadata for github updater in the initital version of my newest plugins  with no review problemes.
https://plugins.svn.wordpress.org/ap-stream-to-rocket/tags/0.0.1/ap-stream-to-rocket.php

**Comment by Zodiac1978** [comment]
Thanks for the PR! After reading [this wiki page](https://github.com/afragen/github-updater/wiki/WordPress.org-Directory), I'm confused: what is the exact use case for this? With `GitHub Branch: master` the Plugin directory would be used and not Github. Maybe I don't get something ...

**Comment by staude** [comment]
if you activate the feature in github updater, you can switch between taged revisions and branches.

<img width="851" alt="githubupdater" src="https://cloud.githubusercontent.com/assets/870951/20117855/8f85d2b4-a602-11e6-8b9e-7cbb87968877.png">

**Comment by Zodiac1978** [comment]
Nice! So you could easily test a branch with a new feature or fix. Great addition. 👍
